/**
 * Demo apartment listings — shown alongside any real Firestore listings
 * so tenants immediately experience the full search/browse/apply flow.
 * Photos are curated Unsplash apartment interiors & exteriors.
 */
import type { ListingDoc } from "@/lib/types/models";

const PHOTOS = {
  living1:    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
  living2:    "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=800&q=80",
  modern1:    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
  modern2:    "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
  exterior1:  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
  exterior2:  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
  luxury1:    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  luxury2:    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
  studio1:    "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
  cozy1:      "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
  bright1:    "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
  loft1:      "https://images.unsplash.com/photo-1574643156929-51fa098b0394?auto=format&fit=crop&w=800&q=80",
};

type DemoListing = ListingDoc & { source: "demo" };

export const DEMO_LISTINGS: DemoListing[] = [
  {
    id: "demo-1", unitId: "", propertyId: "", ownerId: "demo",
    title: "Bright Studio — East Village",
    description: "Renovated studio in the heart of East Village. Exposed brick, updated kitchen, and a private courtyard. Steps from dining, coffee, and parks. Laundry in building. Available now.",
    rent: 1850, beds: 0, baths: 1,
    photos: [PHOTOS.studio1, PHOTOS.modern1],
    city: "New York", state: "NY", zip: "10009",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-2", unitId: "", propertyId: "", ownerId: "demo",
    title: "Spacious 2BR — Williamsburg Loft",
    description: "Stunning loft-style 2-bedroom in Williamsburg with 12-foot ceilings, hardwood floors, and city views. Chef's kitchen, in-unit washer/dryer, rooftop access. Pet-friendly.",
    rent: 3400, beds: 2, baths: 2,
    photos: [PHOTOS.loft1, PHOTOS.living1],
    city: "Brooklyn", state: "NY", zip: "11211",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-3", unitId: "", propertyId: "", ownerId: "demo",
    title: "Modern 1BR — Silver Lake",
    description: "Sleek 1-bedroom in Silver Lake's most walkable block. Stainless appliances, quartz countertops, central A/C. Private balcony with skyline views. Gated parking included.",
    rent: 2200, beds: 1, baths: 1,
    photos: [PHOTOS.modern1, PHOTOS.living2],
    city: "Los Angeles", state: "CA", zip: "90026",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-4", unitId: "", propertyId: "", ownerId: "demo",
    title: "Luxury 3BR — Pacific Heights",
    description: "Premium 3-bedroom flat in iconic Pacific Heights. Original Victorian character meets modern finishes. Formal dining room, updated bathrooms, large garden. 2 parking spots. Rare find.",
    rent: 5800, beds: 3, baths: 2,
    photos: [PHOTOS.luxury1, PHOTOS.luxury2],
    city: "San Francisco", state: "CA", zip: "94115",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-5", unitId: "", propertyId: "", ownerId: "demo",
    title: "River North 1BR + Den",
    description: "Contemporary 1BR + den in sought-after River North. Floor-to-ceiling windows, premium appliances, concierge building. Walk to Magnificent Mile. Fitness center and pool.",
    rent: 2650, beds: 1, baths: 1,
    photos: [PHOTOS.modern2, PHOTOS.exterior1],
    city: "Chicago", state: "IL", zip: "60654",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-6", unitId: "", propertyId: "", ownerId: "demo",
    title: "Cozy 1BR — Wicker Park",
    description: "Charming top-floor 1BR in Wicker Park. Original hardwood, bay windows, exposed brick fireplace. Updated bath and kitchen. Steps from Blue Line. Cats welcome.",
    rent: 1750, beds: 1, baths: 1,
    photos: [PHOTOS.cozy1, PHOTOS.bright1],
    city: "Chicago", state: "IL", zip: "60622",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-7", unitId: "", propertyId: "", ownerId: "demo",
    title: "Luxury High-Rise 2BR — Midtown",
    description: "High-rise 2BR on the 22nd floor with sweeping Peachtree Street views. Hotel-style amenities: valet parking, rooftop pool, 24-hour concierge. Move-in ready.",
    rent: 3100, beds: 2, baths: 2,
    photos: [PHOTOS.luxury2, PHOTOS.exterior2],
    city: "Atlanta", state: "GA", zip: "30308",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-8", unitId: "", propertyId: "", ownerId: "demo",
    title: "Capitol Hill 2BR Rowhouse",
    description: "Classic Capitol Hill rowhouse. 2 large bedrooms, formal living and dining, updated kitchen. Private rear deck and fenced yard. Walk to Eastern Market. Pet-friendly.",
    rent: 3600, beds: 2, baths: 1,
    photos: [PHOTOS.living1, PHOTOS.exterior1],
    city: "Washington", state: "DC", zip: "20003",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-9", unitId: "", propertyId: "", ownerId: "demo",
    title: "Back Bay Studio — Premium Finish",
    description: "Fully renovated studio in prestigious Back Bay. Porcelain tile, custom cabinetry, quartz counters. Roof deck access. Steps from Newbury Street and the Charles River Esplanade.",
    rent: 2400, beds: 0, baths: 1,
    photos: [PHOTOS.studio1, PHOTOS.modern2],
    city: "Boston", state: "MA", zip: "02116",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-10", unitId: "", propertyId: "", ownerId: "demo",
    title: "Capitol Hill 1BR + Parking",
    description: "Well-maintained 1BR in Capitol Hill's Squire Park. New appliances, in-unit laundry, off-street parking included. Quick commute downtown via light rail or I-5.",
    rent: 1900, beds: 1, baths: 1,
    photos: [PHOTOS.bright1, PHOTOS.cozy1],
    city: "Seattle", state: "WA", zip: "98122",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-11", unitId: "", propertyId: "", ownerId: "demo",
    title: "RiNo District Loft — Denver",
    description: "Artist's loft in RiNo's trendiest block. Concrete floors, exposed ductwork, original warehouse windows. Private garage, rooftop terrace. Walking distance to 30+ restaurants and breweries.",
    rent: 2100, beds: 1, baths: 1,
    photos: [PHOTOS.loft1, PHOTOS.modern1],
    city: "Denver", state: "CO", zip: "80205",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-12", unitId: "", propertyId: "", ownerId: "demo",
    title: "Midtown 2BR — Houston",
    description: "Spacious 2BR in Midtown Houston. Private courtyard, community pool and fitness center, assigned parking. Minutes to Medical Center and Museum District. Pets welcome.",
    rent: 1750, beds: 2, baths: 2,
    photos: [PHOTOS.living2, PHOTOS.exterior2],
    city: "Houston", state: "TX", zip: "77006",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-13", unitId: "", propertyId: "", ownerId: "demo",
    title: "South Congress 1BR — Austin",
    description: "New construction 1BR on South Congress Ave. Quartz waterfall island, custom closets, private patio. Walk to ACL Festival grounds, boutiques, and award-winning restaurants.",
    rent: 2050, beds: 1, baths: 1,
    photos: [PHOTOS.modern2, PHOTOS.bright1],
    city: "Austin", state: "TX", zip: "78704",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-14", unitId: "", propertyId: "", ownerId: "demo",
    title: "Little Italy 3BR Penthouse",
    description: "Rare penthouse in Little Italy with private rooftop terrace and 360° city views. 3 large bedrooms, 2.5 baths, chef's kitchen. Valet parking. Walk to the waterfront.",
    rent: 4900, beds: 3, baths: 2,
    photos: [PHOTOS.luxury1, PHOTOS.loft1],
    city: "San Diego", state: "CA", zip: "92101",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-15", unitId: "", propertyId: "", ownerId: "demo",
    title: "Old Town Scottsdale Studio",
    description: "Fully furnished studio near Old Town nightlife and galleries. Resort-style pool, covered parking, on-site laundry. Ideal for remote workers. Flexible lease terms available.",
    rent: 1450, beds: 0, baths: 1,
    photos: [PHOTOS.studio1, PHOTOS.exterior1],
    city: "Scottsdale", state: "AZ", zip: "85251",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-16", unitId: "", propertyId: "", ownerId: "demo",
    title: "Brickell 2BR — Biscayne Bay Views",
    description: "Corner unit 2BR in Brickell Financial District with direct Biscayne Bay views. Floor-to-ceiling glass, spa bath, open-plan living. Building amenities: pool, gym, valet.",
    rent: 4200, beds: 2, baths: 2,
    photos: [PHOTOS.luxury2, PHOTOS.living2],
    city: "Miami", state: "FL", zip: "33131",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-17", unitId: "", propertyId: "", ownerId: "demo",
    title: "South End 1BR — Boston",
    description: "Beautifully renovated 1BR in South End's Victorian brownstone. 10-foot ceilings, custom built-ins, renovated marble bath. Private entrance. Steps from SoWa Art and Design District.",
    rent: 2900, beds: 1, baths: 1,
    photos: [PHOTOS.cozy1, PHOTOS.modern1],
    city: "Boston", state: "MA", zip: "02118",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-18", unitId: "", propertyId: "", ownerId: "demo",
    title: "Montrose 2BR — Garden Apartment",
    description: "Gorgeous 2BR garden apartment in Montrose. Updated kitchen and baths, private garden patio, detached garage. Tree-lined block. Walk to Buffalo Bayou Park and Menil Collection.",
    rent: 2000, beds: 2, baths: 1,
    photos: [PHOTOS.living1, PHOTOS.bright1],
    city: "Houston", state: "TX", zip: "77006",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-19", unitId: "", propertyId: "", ownerId: "demo",
    title: "Pearl District 1BR + Balcony",
    description: "Sleek Pearl District 1BR with a private balcony and city views. Bamboo flooring, Bosch appliances, spa-style bath. Building has EV charging, bike storage, and rooftop terrace.",
    rent: 2300, beds: 1, baths: 1,
    photos: [PHOTOS.modern2, PHOTOS.exterior2],
    city: "Portland", state: "OR", zip: "97209",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-20", unitId: "", propertyId: "", ownerId: "demo",
    title: "Shaw 2BR — New Construction",
    description: "Brand new 2BR in Shaw's hottest block. Smart home tech, keyless entry, Nest thermostat. Designer kitchen with waterfall island. Rooftop deck, dog wash station, bike room.",
    rent: 3400, beds: 2, baths: 2,
    photos: [PHOTOS.luxury1, PHOTOS.modern1],
    city: "Washington", state: "DC", zip: "20001",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-21", unitId: "", propertyId: "", ownerId: "demo",
    title: "Ballard 3BR Family Home",
    description: "Spacious 3BR home in family-friendly Ballard. Hardwood throughout, updated kitchen, large backyard. 2-car garage. Top-rated schools, walkable to shops and Ballard Locks.",
    rent: 3800, beds: 3, baths: 2,
    photos: [PHOTOS.living2, PHOTOS.exterior1],
    city: "Seattle", state: "WA", zip: "98107",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-22", unitId: "", propertyId: "", ownerId: "demo",
    title: "Uptown Charlotte 1BR",
    description: "Modern 1BR in Uptown Charlotte high-rise. Engineered hardwood, quartz counters, stainless appliances. Pool, fitness center, sky lounge. Short walk to Bank of America Stadium.",
    rent: 1850, beds: 1, baths: 1,
    photos: [PHOTOS.modern2, PHOTOS.loft1],
    city: "Charlotte", state: "NC", zip: "28202",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-23", unitId: "", propertyId: "", ownerId: "demo",
    title: "East Nashville 2BR Bungalow",
    description: "Charming renovated bungalow on a tree-lined East Nashville street. New kitchen, updated baths, sunroom, fenced yard. Steps from Five Points restaurants and honky-tonks.",
    rent: 2100, beds: 2, baths: 1,
    photos: [PHOTOS.cozy1, PHOTOS.living1],
    city: "Nashville", state: "TN", zip: "37206",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
  {
    id: "demo-24", unitId: "", propertyId: "", ownerId: "demo",
    title: "Midtown Phoenix Studio + Parking",
    description: "Bright studio near light rail in Midtown Phoenix. Granite counters, stainless appliances, private covered parking. Pool and fitness center on-site. Perfect for ASU downtown campus commuters.",
    rent: 1100, beds: 0, baths: 1,
    photos: [PHOTOS.studio1, PHOTOS.bright1],
    city: "Phoenix", state: "AZ", zip: "85012",
    featured: false, status: "published", createdAt: 0, source: "demo",
  },
];

/** Filter demo listings by search term (city, state, title, zip) */
export function filterDemoListings(term: string): DemoListing[] {
  if (!term.trim()) return DEMO_LISTINGS;
  const lower = term.trim().toLowerCase();
  return DEMO_LISTINGS.filter((l) =>
    [l.title, l.city, l.state, l.zip, l.description]
      .join(" ")
      .toLowerCase()
      .includes(lower),
  );
}
